name: Build 'cde-sample' project
run-name: Build the 'cde-sample' by @${{ github.actor }}

on:
  push:
    branches:
    - master
    - feature/*
  workflow_dispatch:

permissions:
  contents: write
  issues: read
  checks: write
  pull-requests: write

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3 # Reference the major version of a release
      with:
        fetch-depth: 0
        
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11.0.8'
        distribution: 'adopt'
      
    - name: Build with Gradle
      run: ./gradlew build -x test
