name: Build a docker image for cde-sample
run-name: Build the 'cde-sample' by @${{ github.actor }}

on:
  push:
    branches:
    - master
    - feature/*

jobs:
  build:
    runs-on: [cde]
    steps:
    - uses: actions/checkout@v3 # Reference the major version of a release
      with:
        fetch-depth: 0
        
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11.0.8'
        distribution: 'adopt'
      
    - name: Build with Gradle
      run: ./gradlew build -x test

  publish:
    runs-on: [cde]
    needs: [build]
    container:
      image: docker-hub-mirror.linecorp.com/gradle:8.1.0-jdk11
    steps:
      - name: Publish the package
        env:
          GITHUB_REPOSITORY: ${{ env.GITHUB_REPOSITORY }}
          GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
        run: gradle publish

  notify:
    if: ${{ always() }}
    needs: [publish]
    runs-on: [cde]
    steps:
      - name: notify_success
        uses: an/ikameshi@1.0.0
        with:
          channel: infra-ops-dev
          message: '[${{ github.workflow }}] <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|#${{ github.run_number }}> by ${{ github.actor }}'
          nickname: 'Github Actions'
          color: 'green'
          icon_emoji: github
        if: ${{ success() }}
      - name: notify_failure # by curl
        run: |
          curl http://ikameshi.linecorp.com/notice \
          -d 'channel=ee-infra-ops-dev' \
          -d 'nickname=Github Actions' \
          -d 'color=red' \
          -d 'message=[${{ github.workflow }}] <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|#${{ github.run_number }}> by ${{ github.actor }}'
        if: ${{ failure() }}
